Skill.find_or_create_by( name: "Customer Service" , promoted: true )
Skill.find_or_create_by( name: "Computer Experience" , promoted: true )
Skill.find_or_create_by( name: "Use of Office Machinery (i.e. fax, copier )" , promoted: true )
Skill.find_or_create_by( name: "Clerical Duties" , promoted: true )
Skill.find_or_create_by( name: "Foreign Languages" , promoted: true )
Skill.find_or_create_by( name: "Previous Library Experience" , promoted: true )
