module SystemTestHelpers
  # Returns the given prospect fixture as a nested hash similar to that
  # generated by form submission.
  def prospect_fixture_as_request_params(prospect_fixture_key)
    fixture = prospects(prospect_fixture_key)
    prospect_params = fixture.attributes
    prospect_params["enumeration_ids"] = fixture.enumerations.map(&:id)
    prospect_params["available_times_attributes"] = fixture.available_times.as_json(except: [ :id ])
    prospect_params["addresses_attributes"] = fixture.addresses.as_json(except: [ :id ])
    prospect_params["phone_numbers_attributes"] = fixture.phone_numbers.as_json(except: [ :id ])

    prospect_params = prospect_params.except("id", "created_at", "updated_at")
    prospect_params
  end
end
